//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSea24
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RedSeaEntities : DbContext
    {
        public RedSeaEntities()
            : base("name=RedSeaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDesignation> tblDesignations { get; set; }
        public virtual DbSet<tblFTE> tblFTEs { get; set; }
        public virtual DbSet<tblLanguage> tblLanguages { get; set; }
        public virtual DbSet<tblLinkLanguage> tblLinkLanguages { get; set; }
        public virtual DbSet<tblLinkSkill> tblLinkSkills { get; set; }
        public virtual DbSet<tblLinkSystem> tblLinkSystems { get; set; }
        public virtual DbSet<tblLog> tblLogs { get; set; }
        public virtual DbSet<tblPC> tblPCs { get; set; }
        public virtual DbSet<tblReview> tblReviews { get; set; }
        public virtual DbSet<tblSkill> tblSkills { get; set; }
        public virtual DbSet<tblSystem> tblSystems { get; set; }
        public virtual DbSet<tblTeam> tblTeams { get; set; }
        public virtual DbSet<tblTeamGroup> tblTeamGroups { get; set; }
        public virtual DbSet<vAllEmpoyee> vAllEmpoyees { get; set; }
    }
}
