//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSea24
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFTE
    {
        public tblFTE()
        {
            this.tblFTE1 = new HashSet<tblFTE>();
            this.tblLinkLanguages = new HashSet<tblLinkLanguage>();
            this.tblLinkSkills = new HashSet<tblLinkSkill>();
            this.tblLinkSystems = new HashSet<tblLinkSystem>();
            this.tblLogs = new HashSet<tblLog>();
            this.tblReviews = new HashSet<tblReview>();
            this.tblReviews1 = new HashSet<tblReview>();
        }
    
        public long Id { get; set; }
        public int Team { get; set; }
        public int Designation { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Cisco { get; set; }
        public int PC { get; set; }
        public string Code { get; set; }
        public string FingerPrint { get; set; }
        public Nullable<long> DirectReport { get; set; }
        public string Phone { get; set; }
        public byte[] Photo { get; set; }
        public string Email { get; set; }
        public string PassKey { get; set; }
        public string Authority { get; set; }
        public bool Active { get; set; }
        public string Notes { get; set; }
        public System.DateTime HireDate { get; set; }
    
        public virtual tblDesignation tblDesignation { get; set; }
        public virtual ICollection<tblFTE> tblFTE1 { get; set; }
        public virtual tblFTE tblFTE2 { get; set; }
        public virtual tblPC tblPC { get; set; }
        public virtual tblTeam tblTeam { get; set; }
        public virtual ICollection<tblLinkLanguage> tblLinkLanguages { get; set; }
        public virtual ICollection<tblLinkSkill> tblLinkSkills { get; set; }
        public virtual ICollection<tblLinkSystem> tblLinkSystems { get; set; }
        public virtual ICollection<tblLog> tblLogs { get; set; }
        public virtual ICollection<tblReview> tblReviews { get; set; }
        public virtual ICollection<tblReview> tblReviews1 { get; set; }
    }
}
