//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSea24
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLinkSkill
    {
        public long Id { get; set; }
        public long FTE { get; set; }
        public int Skill { get; set; }
    
        public virtual tblFTE tblFTE { get; set; }
        public virtual tblSkill tblSkill { get; set; }
    }
}
