//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSea24
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPC
    {
        public tblPC()
        {
            this.tblFTEs = new HashSet<tblFTE>();
        }
    
        public int Id { get; set; }
        public string PCName { get; set; }
        public string Screen1 { get; set; }
        public string Screen2 { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<tblFTE> tblFTEs { get; set; }
    }
}
