//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSea24
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        public long Id { get; set; }
        public System.DateTime cDate { get; set; }
        public long FTE { get; set; }
        public string cType { get; set; }
        public string Details { get; set; }
        public long cUser { get; set; }
    
        public virtual tblFTE tblFTE { get; set; }
        public virtual tblFTE tblFTE1 { get; set; }
    }
}
