//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSea24
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystem
    {
        public tblSystem()
        {
            this.tblLinkSystems = new HashSet<tblLinkSystem>();
        }
    
        public int Id { get; set; }
        public string SystemName { get; set; }
    
        public virtual ICollection<tblLinkSystem> tblLinkSystems { get; set; }
    }
}
