//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSea24
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAllEmpoyee
    {
        public long Id { get; set; }
        public string TeamGroup { get; set; }
        public string Team { get; set; }
        public string Designation { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Cisco { get; set; }
        public string Code { get; set; }
        public string FingerPrint { get; set; }
        public string DirectReport { get; set; }
        public string Phone { get; set; }
        public byte[] Photo { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
    }
}
